blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_funktion, name='search_url'),
    path('news/<slug:slug>/', views.post_detail, name='post_detail_url'),
    path('news/<slug:slug>/comment/', views.comment, name='comment'),
    path('categories/<slug:slug>/', views.category_detail, name='category_detail_url'),
    path('register/', views.register, name='register'),
]

news_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), #127.0.0.1:8000/admin
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #127.0.0.1:8000/accounts
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField("Sarlovha", max_length=255)
    slug = models.SlugField("Silka", unique=True)
    image = models.ImageField("Rasm", blank=True, null=True)
    

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'

    def get_absolut_url(self):
        return reverse('category_detail_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField("Sarlovha", max_length=255)
    slug = models.SlugField("Silka", unique=True)
    image = models.ImageField("Rasm", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Kategoriya")
    content = models.TextField("Text")
    date = models.DateTimeField("Sana",default=timezone.now)
    publish = models.BooleanField("Taqdim etish", default=False)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Postlar'

    def get_absolut_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Avtor")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Yangilik")
    text = models.TextField("Kommentariya")
    data = models.DateTimeField("Sana", default=timezone.now)

    class Meta:
        verbose_name = "Komentariya"
        verbose_name_plural = "Komentariyalar"

    def __str__(self):
        return self.user.username

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Parol", required=True, widget=forms.PasswordInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Takroran", required=True, widget=forms.PasswordInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label="Email", required=True, widget=forms.EmailInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label="Ism", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label="Familiya", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))


    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.last_name = self.cleaned_data["last_name"]
        user.first_name = self.cleaned_data["first_name"]

        if commit:
            user.save()
            return user

blog/views.py
from django.shortcuts import render, redirect, reverse
from .models import Post, Category
from django.db.models import Q
from django.http import request
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout

def index(request):
    posts = Post.objects.order_by('id')
    return render(request, 'blog/index.html', {'posts':posts})  #project/app/templates/blog/index.html

def search_funktion(request):
    query = request.GET.get('search_input')
    posts = Post.objects.filter(Q(title__icontains = query))
    return render(request, 'blog/search.html', {'query': query, 'posts': posts})

def post_detail(request, slug):
    post = Post.objects.get(slug__exact = slug)
    return render(request, 'blog/post_detail.html', {'post': post})

def category_detail(request, slug):
    category = Category.objects.get(slug__exact = slug)
    return render(request, 'blog/category_detail.html', {'category': category})

def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('login')
        else:
            form = RegisterForm()
        return render(request, 'blog/register.html', {'form': form})
    return redirect('index')


def comment(request, slug):
    post = Post.objects.get(slug__exact = slug)
    
    if request.method == "POST":
        post.comment_set.create(
            user = request.user,
            text = request.POST.get('text')
        )
        return redirect(reverse('post_detail_url', kwargs={'slug': post.slug}))
    return redirect(reverse('post_detail_url', kwargs={'slug': post.slug}))

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Bekorchilar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'index' %}">Asosiy</a>
              </li>
              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Registrasiya</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Kirish</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Chiqish</a>
              </li>
              {% endif %}
            </ul>
            <form action="{% url 'search_url' %}" method="GET" class="d-flex">
              <input name="search_input" required class="form-control me-2" type="search" placeholder="Qidiruv" aria-label="Search">
              <button class="btn btn-outline-success">Qidiruv</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="/static/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.category.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
           
            {% if category.image.url != null %}
                <img src="{{category.image.url}}" style="width: 100%;" alt="">
            {% endif %}
            <h3>{{category.title}}</h3>
            <hr>
            <div class="row">
                {% for post in category.post_set.all %}
                <div class="col-md-4">
                  <div class="card">
                    {% if post.image.url != null %}
                      <img style="height: 300px; object-fit: cover" src="{{post.image.url}}" class="card-img-top" alt="...">
                      {% endif %}
                      <div class="card-body">
                        <a href="{{post.get_absolut_url}}">
                          <h5 class="card-title">{{post.title}}</h5>
                        </a>
                        <p class="card-text">{{post.content|slice:"0:100"}}</p>
                        <a href="{{post.category.get_absolut_url}}" class="btn btn-primary">{{post.category.title}}</a>
                      </div>
                      
                    </div>
                </div>
              {% endfor %}
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h3 class="text-center">{{post.title}}</h3>
            {% if post.image.url != null %}
                <img src="{{post.image.url}}" style="width: 100%;" alt="">
            {% endif %}
            <p>{{post.content}}</p>
            <p class="text-right">
                <i>{{post.date|date:"d F, Y"}}</i>
            </p>
            <hr>
            <p>
                <i>Kommentariyalar: {{post.comment_set.count}}</i>
            </p>
            <h3>Kommentariya qoldirish:</h3>
            {% if user.is_authenticated %}
            <form action="{% url 'comment' post.slug %}" method="POST">
                {% csrf_token %}
                <p>
                    <textarea name="" id="" cols="30" rows="10" class="form-control"></textarea>
                </p>
                <p class="text-right">
                    <button class="btn btn-outline-primary">Yuborish</button>
                </p>
            </form>
            {% else %}
            <p>Kommentariya qoldirish uchun <a href="{% url 'register' %}">registrasya qiling yoki <a href="{% url 'login' %}">kiring</a></a></p>
            {% endif %}
            <hr>
            {% for comment in post.comment_set.all %}
            <div class="col-md-12">
                <h3>{{comment.user.username}}</h3>
                <p>{{comment.text}}</p>
                <p class="text-right">{{comment.date|timesince}} oldin</p>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block title %}
Registratsiya
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Registratsiya</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}   

{% block title %}
Qidiruv bo'yicha: {{query}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                <div class="col-md-4">
                    {% if post.image.url != null %}
                    <img src="{{post.image.url}}" alt="">
                    {% endif %}
                    <h3 class="text-center">{{post.title}}</h3>
                </div>
                {% empty %}
                <h2>Suralgan "{{query}}" bo'yicha hech narsa topilmadi</h2>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}